### ISSUE TITLE
GUI Research

### ISSUE THREAD

**Issue by joemdevlin** [jake-bickle/rlcard#10]
Team needs to investigate what technology to use and come up with potential UI mockup

**Comment by jneckar** [comment]
Some potential features I think it would be good to have in a GUI:

Interface to select environment, agents, number of evaluations, etc
Status bar showing evaluation progress
After evaluation, plot of overall performance
Plot of performance in each position (small blind, big blind)
Possibly a further breakdown of performance, for example a way to query how much was won or lost with a specific hand, etc
Round robin mode for evaluating multiple agents against each other - it could output a chart that shows win/loss rate between each agent, and each agents overall win/loss rate.
Calculation of confidence intervals for results based on number of hands played and standard deviation of chips won/lost

**Comment by joemdevlin** [comment]
I looked into some ways to dynamically update the webpage based on the ongoing game play.  It looks like the general consensus is to use jquery + redis stack queue:
https://www.shanelynn.ie/asynchronous-updates-to-a-webpage-with-flask-and-socket-io/
https://flask.palletsprojects.com/en/1.1.x/patterns/jquery/
https://realpython.com/flask-by-example-updating-the-ui/

**Comment by joemdevlin** [comment]
tkiter mock interface is in the GUI branch. 
To Run: python GUI\gui_main.py
